# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview', '0002_auto_20170223_1055'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('reviewManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
